### create new speaker localhost
POST http://localhost:8080/conference/api/info/speaker
Content-Type: application/json
accept: application/json

{
  "name": "Mogens Lykketoft",
  "profession": "CEO",
  "gender": "m"


}

### create new talk localhost
POST http://localhost:8080/conference/api/info/talk
Content-Type: application/json
accept: application/json

{
  "topic": "How to survive in the wilderness",
  "duration": 90
}

### create new conference localhost
POST http://localhost:8080/conference/api/info/conference
Content-Type: application/json
accept: application/json

{
  "name": "Back to the wilderness",
  "location": "Rønne",
  "capacity": 10,
  "date": "2-2-23",
  "time": "00:10:00"
}

### Edit talk localhost
PUT http://localhost:8080/conference/api/info/talk
Content-Type: application/json
accept: application/json

{
  "id": 5,
  "topic": "How to survive in the wilderness",
  "duration": 90,
  "propsList": "Music, pointers"
}

### Delete talk localhost
DELETE http://localhost:8080/conference/api/info/talk
Content-Type: application/json
accept: application/json

{
  "id": 5,
  "topic": "How to survive in the wilderness",
  "duration": 90,
  "propsList": "Music, pointers"
}
